#!/bin/sh
rm -rf docs site
packages="core ammo three pixi matter rapier2d rapier3d"
for str in $packages; do
  mkdir -p src/$str
  cp -R ../packages/$str/src/* src/$str
done

npm run run-doc-gen
rm -rf src
find docs -type f -name index.md -exec sed -i 's/\/modules/\/gg-web-engine\/modules/g' {} \; # fix paths, generated by docs-ts-mkdocs

# the generated home page is an empty stub: replace it with the hand-written landing page
cp landing.md docs/index.md
mkdir -p docs/assets
cp assets/banner.png docs/assets/banner.png

# llms.txt / llms-full.txt for AI coding agents, served from the site root; generated from the
# app-development skill, landing.md and examples/ (see etc/generate_agent_docs.mjs)
node ../etc/generate_agent_docs.mjs --llms docs

mkdocs build
