name: Unit tests
on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, unlabeled]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test core
        working-directory: ./packages/core
        run: npm i && npm run test

      - name: Switch libraries to use local core package
        working-directory: ./etc
        run: bash switch_libs_to_local_core.sh

      - name: Test ammo
        working-directory: ./packages/ammo
        run: npm run build && npm run test

      - name: Build matter
        working-directory: ./packages/matter
        run: npm run build

      - name: Build pixi
        working-directory: ./packages/pixi
        run: npm run build

      - name: Test rapier2d
        working-directory: ./packages/rapier2d
        run: npm run build && npm run test

      - name: Test rapier3d
        working-directory: ./packages/rapier3d
        run: npm run build && npm run test

      - name: Build three
        working-directory: ./packages/three
        run: npm run build
