name: Release new version

on:
  push:
    branches:
      - main

jobs:
  release-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get commit message
        id: get_commit_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          echo "commit_message=$COMMIT_MESSAGE" >> $GITHUB_ENV

      - name: Extract version string
        id: extract_version
        run: |
          if [[ "$commit_message" =~ ^\[pre-release\]\ \[([0-9]+\.[0-9]+\.[0-9]+)\] ]]; then
            VERSION="${BASH_REMATCH[1]}"
            echo "version=$VERSION" >> $GITHUB_ENV
          else
            echo "Commit message does not match the pre-release pattern, exiting..."
            exit 0
          fi

      - name: Setup python
        uses: getsentry/action-setup-venv@v2.1.0
        with:
          python-version: 3.10.7
          cache-dependency-path: ./documentation/requirements.txt
          install-cmd: pip install -r ./documentation/requirements.txt
          venv-directory: ./documentation/.venv

      - name: Publish
        run: |
          chmod +x ./etc/publish_new_version.sh
          ./etc/publish_new_version.sh ${{ env.version }}

      - name: Update version in git
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '${{ env.version }} release'
          push_options: --force
          tagging_message: ${{ env.version }}
